/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#121317',
        'surface-dim': '#121317',
        'surface-bright': '#38393d',
        'surface-container-lowest': '#0d0e12',
        'surface-container-low': '#1a1b1f',
        'surface-container': '#1e1f23',
        'surface-container-high': '#292a2e',
        'surface-container-highest': '#343539',
        'on-surface': '#e3e2e7',
        'on-surface-variant': '#c1c6d7',
        'inverse-surface': '#e3e2e7',
        'inverse-on-surface': '#2f3034',
        'outline': '#8b90a0',
        'outline-variant': '#414755',
        'surface-tint': '#adc6ff',
        'primary': '#adc6ff',
        'on-primary': '#002e69',
        'primary-container': '#4b8eff',
        'on-primary-container': '#00285c',
        'inverse-primary': '#005bc1',
        'secondary': '#c8c6c5',
        'on-secondary': '#313030',
        'secondary-container': '#4a4949',
        'on-secondary-container': '#bab8b7',
        'tertiary': '#c8c6c8',
        'on-tertiary': '#303032',
        'tertiary-container': '#919092',
        'on-tertiary-container': '#29292b',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#121317',
        'on-background': '#e3e2e7',
      },
      fontFamily: {
        'space': ['"Space Grotesk"', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
      },
      spacing: {
        'xs': '8px',
        'sm': '16px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
      },
      maxWidth: {
        'container': '1280px',
      }
    },
  },
  plugins: [],
}
